### ISSUE TITLE
gem install ox -v '2.7.0' error while  installing openxml-docx 

### ISSUE THREAD

**Issue by matt212** [openxml/openxml-docx#67]
Hi, 
we are facing below error from attached screenshot
any pointers on how to resolved , 
please note we tried installing dependencies 'ox -v '2.7.0' after clearing gem cache !
![test](https://user-images.githubusercontent.com/1698139/30742533-1ce047f8-9fb7-11e7-843f-9b1b514a6afd.png)
our system configuration is
OS:      Ubuntu 12 LTS 
arch :    64 bit

**Comment by boblail** [comment]
When you did `gem install ox -v '2.7.0'`, did you also get these C errors?

What happens if you try `gem install ox` (there's a new version as of today)? Same problem?

And what happens if you try `gem install openxml-docx -v '0.11.0.rc'`? In the `0.11.0` of openxml-docx, we lock the gemspec to different version of Ox.

Finally, could it be because you're still on Ruby 2.1? Is it possible for you to upgrade to Ruby 2.3 or 2.4?

**Comment by kobsy** [comment]
Looking at the list of commits on [ohler55/ox](https://github.com/ohler55/ox/commits/master), it looks like compatibility with Ruby 2.2 was attempted and then perhaps achieved(?) with the version `0.8.0` release. So if you can't upgrade versions of Ruby, you may also try the newer version of Ox.

**Comment by matt212** [comment]
thanks @boblail  it worked thanks so much for solving this issue
